# Generated by Django 4.2.2 on 2023-06-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardsmodel',
            options={'permissions': (('es_miembro_1', 'Es miembro con prioridad 1'),)},
        ),
        migrations.AddField(
            model_name='boardsmodel',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='boardsmodel',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardsmodel',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
