# Generated by Django 4.2.2 on 2023-06-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_boardsmodel_options_boardsmodel_creado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardsmodel',
            options={'ordering': ['-creado'], 'permissions': (('es_miembro_1', 'Es miembro con prioridad 1'),), 'verbose_name': 'tablero', 'verbose_name_plural': 'tableros'},
        ),
        migrations.AddField(
            model_name='boardsmodel',
            name='estatus',
            field=models.CharField(choices=[('PI', 'Por iniciar'), ('I', 'Iniciado'), ('T', 'Terminado')], default='PI', max_length=20),
        ),
    ]
